version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: awsecr
          create-repo: true
          repo: $CIRCLE_PROJECT_REPONAME

